party_maker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('polls.urls'))
]
urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login', views.login_page, name='login'),
    url(r'^vk', views.vk_handler, name='vk_handler'),
    url(r'^new_poll', views.new_poll, name='new_poll'),
    url(r'^polls_list', views.polls_list, name='polls_list'),
    url(r'^vote_end', views.vote_end, name='vote_end'),
    url(r'^confirm_change_poll$', views.confirm_change_poll, name='confirm_change_poll'),
]

polls/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User, UserManager

class SocialTypes(models.Model):
    '''Social networks types, now vk.com only'''
    name = models.CharField(max_length=50)

class UserSocialProfile(models.Model):
    '''Users social networks profiles'''
    user = models.ForeignKey('auth.User')
    social_type = models.ForeignKey(SocialTypes, on_delete=models.CASCADE)
    social_id = models.CharField(max_length=50)
    social_first_name = models.CharField(max_length=50, null=True)
    social_last_name = models.CharField(max_length=50, null=True)
    social_photo_url = models.CharField(max_length=100, null=True)

class Poll(models.Model):
    '''The polls'''
    error_css_class = 'error'
    DRINKS = (
        ('v', 'Водка'),
        ('b', 'Пиво'),
        ('j', 'Сок'),
        ('w', 'Вино'),
        ('l', 'Вино'),
    )
    PRESENCE_STATUSES = (
        ('t', 'Приду'),
        ('f', "Не приду"),
    )
    user = models.ForeignKey('auth.User')
    drink = models.CharField(max_length=1, choices=DRINKS)
    presence = models.CharField(max_length=1, choices=PRESENCE_STATUSES)

polls/forms.py
from django import forms
from .models import Poll

class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ('drink', 'presence')

polls/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from .classes.vk_social import vk_social
from .classes.polls_help import polls_help
from django.conf import settings
from django.core.mail import send_mail
from .forms import PollForm
from .models import User, Poll
from django.contrib.auth import logout

def index(request):
    '''index page. Now - only routing'''
    if request.user.is_authenticated():
        polls_help_obj = polls_help()

        if polls_help_obj.is_party_manager(request):
            return redirect('polls.views.polls_list')
        else:
            return redirect('polls.views.new_poll')

    else:
        return redirect('polls.views.login_page')

def login_page(request):
    '''User login page'''
    return render(request, 'auth/login_page.html', {'client_id': settings.VK_CLIENT_ID, 'redirect_url': settings.VK_REDIRECT_URL})

def vk_handler(request):
    if request.method == "GET" and 'code' in request.GET:
        vk_auth_code = request.GET['code']
        vk_user_obj = vk_social(vk_auth_code)
        vk_auth_result = vk_user_obj.register_and_login_user(request)

        if vk_auth_result:
            polls_help_obj = polls_help()

            if polls_help_obj.is_party_manager(request):
                # manager
                return redirect('polls.views.polls_list')
            else:
                # represent new_poll
                return redirect('polls.views.new_poll')
        else:
            # auth error !!!!
            return redirect('polls.views.login_page')
    else:
        return redirect('polls.views.login_page')

def new_poll(request):
    '''Arrange new poll representation'''
    if request.user.is_authenticated():
        if request.method == "POST":
            form = PollForm(request.POST)

            if form.is_valid():
                poll = form.save(commit=False)
                poll.user = request.user
                poll.save()
                send_mail('Новый результат голосования', 'Получен новый результат голосования!', settings.EMAIL_HOST_USER, [settings.PARTY_MANAGER_EMAIL])
                return render(request, 'polls/vote_end.html', {})
            else:
                # Return error
                polls_help_obj = polls_help()
                new_poll_params = polls_help_obj.arrange_poll_form(request, form)
                return render(request, 'polls/new_poll.html', new_poll_params)
        else:
            # Represent the form
            #find previous poll
            user = request.user
            polls = Poll.objects.filter(user=user)

            if polls:
                # ask
                return redirect('polls.views.confirm_change_poll')
            else:
                # represent the form
                form = PollForm()
                polls_help_obj = polls_help()
                new_poll_params = polls_help_obj.arrange_poll_form(request, form)
                return render(request, 'polls/new_poll.html', new_poll_params)
    # is not auth.
    else:
        return redirect('polls.views.login_page')

def confirm_change_poll(request):
    '''Arrange requust to next step if the poll is exist'''
    if request.method == "POST":
        # if it is appropriate
        if 'next_choice' in request.POST:

            if len(request.POST['next_choice']) == 2:
                # no
                send_mail('Новый результат голосования', 'Удален старый и получен новый результат голосования!',settings.EMAIL_HOST_USER, [settings.PARTY_MANAGER_EMAIL])
                user = request.user
                poll = Poll.objects.get(user=user)
                poll.delete()
                return redirect('polls.views.new_poll')
            elif len(request.POST['next_choice']) == 3:
                # yes
                logout(request)
                return render(request, 'polls/vote_end.html')
            # error
            else:
                return redirect('polls.views.new_poll')
    # represent
    else:
        return render(request, 'polls/confirm_change_poll.html', {})

def polls_list(request):
    '''Returns polls list for app manager'''
    polls_help_obj = polls_help()

    if polls_help_obj.is_party_manager(request):
        users = User.objects.all()
        return render(request, 'polls/polls_list.html', {'users': users})
    else:
        return redirect('polls.views.new_poll')

def vote_end(request):
    '''Congratulations!'''
    if request.user.is_authenticated():
        polls_help_obj = polls_help()

        if polls_help_obj.is_party_manager(request):
            return redirect('polls.views.polls_list')
        else:
            logout(request)
            return render(request, 'polls/vote_end.html', {})

    else:
        return redirect('polls.views.login_page')

polls/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Party Maker</title>

    <link rel="stylesheet" href="{% static 'css/polls.css' %}">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="wrapper">
        {% block content %}{% endblock %}
        {% if user.is_authenticated %}
        {% endif %}
    </div>
  </body>
</html>

polls/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <h1>Hey Nico!</h1>

    <a href="https://oauth.vk.com/authorize?client_id={{ client_id }}&display=page&redirect_uri={{ redirect_url }}&scope=friends&response_type=code&v=5.53" title="Зайти через ВКонтакте">
        Зайти через ВКонтакте</a>
    <br/>порпроп

{% endblock %}

polls/templates/polls/confirm_change_poll.html
{% extends "base.html" %}

{% block content %}
    <h2>Ранее вы уже голосовали, удалить старый ответ и голосовать заново?</h2>
     <form method="POST" class="next_choice-form form">
        {% csrf_token %}
        <input type="submit" class="submit" name="next_choice" value="Да">
        <input type="submit" class="submit" name="next_choice" value="Нет">
     </form>
{% endblock %}

polls/templates/polls/new_poll.html
{% extends "base.html" %}

{% block content %}
    <h1>Здравствуйте, {{ vk_social_user.social_first_name }}!</h1>
    <form method="POST" class="new-poll-form form">
        {% csrf_token %}
        <label for="{{ form.presence.index }}">Вы придете на вечеринку?</label>
        <div {% if form.presence.errors %}class="error"{% endif %}>
        {{ form.presence }}
        </div>
        <label for="{{ form.drink.index }}">Выберете напиток, который бы вы предпочли:</label>
        <div {% if form.drink.errors %}class="error"{% endif %}>
        {{ form.drink }}
        </div>
        <button type="submit" class="submit">Отправить ответ</button>
    </form>
{% endblock %}

polls/templates/polls/polls_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Ответы</h1>
    {% for user in users %}
        {% for social_profile in user.usersocialprofile_set.all %}
            {% for poll in user.poll_set.all %}
                {% if social_profile.social_id and poll.presence and poll.drink %}
                    <div class="col">
                        <img src="{{ social_profile.social_photo_url }}" />
                    </div>
                    <div class="col">
                        <h3>{{ social_profile.social_first_name }} {{ social_profile.social_last_name }}</h3>
                    </div>
                    <blockquote>"{{ poll.get_presence_display }} на вечеринку.
                    {% if poll.presence == 't' %}
                        Предпочту пить <span class="lowercase">{{ poll.get_drink_display }}</span>."</blockquote>
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% endfor %}
{% endblock %}

polls/templates/polls/vote_end.html
{% extends "base.html" %}

{% block content %}
    <h1>Спасибо за участие в голосовании!</h1>
{% endblock %}